version: 2.0

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: lint
  py36-core:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-core
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core
  py38-core:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-core
  py39-core:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-core
  py310-core:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-core
  pypy3-core:
    <<: *common
    docker:
      - image: pypy
        environment:
          TOXENV: pypy3-core
  py36-backends-coincurve7:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve7
  py37-backends-coincurve7:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve7
  py38-backends-coincurve7:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve7
  py39-backends-coincurve7:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve7
  py310-backends-coincurve7:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve7
  py36-backends-coincurve8:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve8
  py37-backends-coincurve8:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve8
  py38-backends-coincurve8:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve8
  py39-backends-coincurve8:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve8
  py310-backends-coincurve8:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve8
  py36-backends-coincurve9:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve9
  py37-backends-coincurve9:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve9
  py38-backends-coincurve9:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve9
  py39-backends-coincurve9:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve9
  py310-backends-coincurve9:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve9
  py36-backends-coincurve10:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve10
  py37-backends-coincurve10:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve10
  py38-backends-coincurve10:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve10
  py39-backends-coincurve10:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve10
  py310-backends-coincurve10:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve10
  py36-backends-coincurve11:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve11
  py37-backends-coincurve11:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve11
  py38-backends-coincurve11:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve11
  py39-backends-coincurve11:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve11
  py310-backends-coincurve11:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve11
  py36-backends-coincurve12:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve12
  py37-backends-coincurve12:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve12
  py38-backends-coincurve12:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve12
  py39-backends-coincurve12:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve12
  py310-backends-coincurve12:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve12
  py36-backends-coincurve13:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve13
  py37-backends-coincurve13:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve13
  py38-backends-coincurve13:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve13
  py39-backends-coincurve13:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve13
  py310-backends-coincurve13:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve13
  py36-backends-coincurve14:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve14
  py37-backends-coincurve14:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve14
  py38-backends-coincurve14:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve14
  py39-backends-coincurve14:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve14
  py310-backends-coincurve14:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve14
  py36-backends-coincurve15:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-backends-coincurve15
  py37-backends-coincurve15:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-backends-coincurve15
  py38-backends-coincurve15:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV: py38-backends-coincurve15
  py39-backends-coincurve15:
    <<: *common
    docker:
      - image: circleci/python:3.9
        environment:
          TOXENV: py39-backends-coincurve15
  py310-backends-coincurve15:
    <<: *common
    docker:
      - image: circleci/python:3.10
        environment:
          TOXENV: py310-backends-coincurve15
workflows:
  version: 2
  test:
    jobs:
      - lint
      - py36-core
      - py37-core
      - py38-core
      - py39-core
      - py310-core
      - pypy3-core
      - py36-backends-coincurve7
      - py37-backends-coincurve7
      - py38-backends-coincurve7
      - py39-backends-coincurve7
      - py310-backends-coincurve7
      - py36-backends-coincurve8
      - py37-backends-coincurve8
      - py38-backends-coincurve8
      - py39-backends-coincurve8
      - py310-backends-coincurve8
      - py36-backends-coincurve9
      - py37-backends-coincurve9
      - py38-backends-coincurve9
      - py39-backends-coincurve9
      - py310-backends-coincurve9
      - py36-backends-coincurve10
      - py37-backends-coincurve10
      - py38-backends-coincurve10
      - py39-backends-coincurve10
      - py310-backends-coincurve10
      - py36-backends-coincurve11
      - py37-backends-coincurve11
      - py38-backends-coincurve11
      - py39-backends-coincurve11
      - py310-backends-coincurve11
      - py36-backends-coincurve12
      - py37-backends-coincurve12
      - py38-backends-coincurve12
      - py39-backends-coincurve12
      - py310-backends-coincurve12
      - py36-backends-coincurve13
      - py37-backends-coincurve13
      - py38-backends-coincurve13
      - py39-backends-coincurve13
      - py310-backends-coincurve13
      - py36-backends-coincurve14
      - py37-backends-coincurve14
      - py38-backends-coincurve14
      - py39-backends-coincurve14
      - py310-backends-coincurve14
      - py36-backends-coincurve15
      - py37-backends-coincurve15
      - py38-backends-coincurve15
      - py39-backends-coincurve15
      - py310-backends-coincurve15
